app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_restful import Api
from flask_marshmallow import Marshmallow


db = SQLAlchemy()
api = Api()
ma = Marshmallow()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    db.init_app(app)
    ma.init_app(app)

    from main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import Flask, request, make_response, redirect, url_for, \
                    render_template, session, flash, current_app, abort, jsonify
from . import main
from .. import db
from ..utils import do_all
from webargs.flaskparser import use_args, use_kwargs, parser
from argument import *
import numpy as np
import pandas as pd


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/video')
def video():
    return render_template('video.html')

@main.route('/where')
def where():
    return render_template('where.html')

@main.route('/space')
def space():
    return render_template('space.html')

@main.route('/earth')
def earth():
    return render_template('earth.html')

@main.route('/appliance/<float:Power>')
def appliance(Power):
    Power = Power
    return render_template('appliance.html', Power=Power)


@main.route('/api/v1/predict')
@use_kwargs(features)
def predict(barometric, humidity, speed, temp, direction, eff, panel_area):
    X = np.array([barometric, humidity, speed, temp, direction])
    # X= pd.Series({"barometric": barometric, "humidity": humidity,
    #               "speed": speed, "temp": temp, "direction":direction})
    total = do_all(X, eff, panel_area)
    total = total[0]
    print total
    return jsonify({"total": str(total)})

app/templates/earth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SimpleSpace</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto:300,400|Questrial|Satisfy">
    <link rel="stylesheet" type="text/css" href="static/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="static/css/style.css">

  </head>
  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" >
    <div id="overlay"></div>
  <div class="header">
      <div class="bg-color">
        <header id="main-header">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lauraMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('main.index') }}">SimpleSolar</a>
            </div>
            <div class="collapse navbar-collapse" id="lauraMenu">
              <ul class="nav navbar-nav navbar-right navbar-border">
                <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>




  <section id="contact" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="contact-sec text-center">
            <h2>Hey <span class="deco">Earth dweller!</span> Welcome!</h2>

          </div>
        </div>


              <div>
                <img src="static/img/kkk.jpg">
                <label>Is your solar panel as big as a piece of this? or twice or half? </label>
                <input id="size" type="number" value="1" placeholder="1" name="institution">
              </div>
              <div class="form-group"><br>
                <label>Select Your solar panel manufacturer</label><br>
                <select id="eff" class="form-control-inline" name="day">
                  <option>Product Manufacturer</option>
                  <option>Sunpower</option>
                  <option>LG Electronics</option>
                  <option>SunEdison</option>
                  <option>First-Solar</option>
                  <option>TopSCN</option>
                  <option>SchucoUSA</option>
                </select>
              </div>
              <div class="text-center" >
                <button type="submit" class="btn btn-primary btn-lg" onclick="Earth()">Proceed to select appliances</button>
              </div>


      </div>
    </div>
  </section>
  <footer class="footer-2 text-center-xs bg--white">
    <div class="container">
      <!--end row-->
      <div class="row">
          <div class="col-md-6">
              <div class="footer">
                  © Copyright SimpleSolar. All Rights Reserved
                    <div class="credits">
                        <!--
                            All the links in the footer should remain intact.
                            You can delete the links only if you purchased the pro version.
                            Licensing information: https://bootstrapmade.com/license/
                            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Laura
                        -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade.com</a>
                    </div>
              </div>
          </div>

      </div>
      <!--end row-->
    </div>
  </footer>

    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/jquery.easing.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/jquery.bxslider.min.js"></script>
    <script src="static/js/wow.js"></script>
    <script src="static/js/custom.js"></script>
    <script>
      function Earth(){
        $("body").append('<div id="overlay" style="background-color:grey;position:absolute;top:0;left:0;height:100%;width:100%;z-index:999></div>');
        size = $("#size").val() * 1.612;
        var man = $("#eff").val();
        efficiency=0;
        switch (man) {
          case "Sunpower":
            efficiency = 0.02207
            break;
          case "LG Electronics":
              efficiency = 0.01849
              break;
          case "SunEdison":
                efficiency = 0.1840
                break;
          case "First-Solar":
                  efficiency = 0.01833
                  break;
          case "TopSCN":
                efficiency = 0.01404
                    break;
          case "SchucoUSA":
                efficiency = 0.00629
                break;
          default:
                efficiency = 0.005
                break;
        }
        getLocation();
      };

      function getLocation() {
        $.getJSON('https://freegeoip.net/json/')
     .done (function(location)
     {
          lat=location.latitude;
          lon=location.longitude;
          console.log(lat);
          console.log(lon);
          getWeather()
      });
    }

    function getWeather() {
      $.getJSON('http://api.openweathermap.org/data/2.5/find?lat='+ lat +'&lon='+lon+'&units=imperial&APPID=b5805c5e41f9c61aeaddb25212aa96b0')
   .done (function(location)
   {
     temp = location.list[0].main.temp;
     humidity = location.list[0].main.humidity;
     pressure = location.list[0].main.pressure;
     wind_speed = location.list[0].wind.speed;
     wind_direction = location.list[0].wind.deg || 0;

     getPower()
    });
    }

    function getPower() {
      $.getJSON('http://localhost:5000/api/v1/predict?barometric='+pressure+'&humidity='+humidity+'&speed='+wind_speed+'&temp='+temp+'&eff='+efficiency+'&panel_area='+size+'&direction='+wind_direction)
   .done (function(power)
   {
     $(location).attr('href', 'http://localhost:5000/appliance/'+power.total * 1000)
    });
    }
    </script>

  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laura Bootstrap Theme</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto:300,400|Questrial|Satisfy">
    <link rel="stylesheet" type="text/css" href="static/css/font-awesome.min.css'">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/animate.css" >
    <link rel="stylesheet" type="text/css" href="static/css/style.css">

    <!-- =======================================================
        Theme Name: Laura
        Theme URL: https://bootstrapmade.com/laura-free-creative-bootstrap-theme/
        Author: BootstrapMade.com
        Author URL: https://bootstrapmade.com
    ======================================================= -->
  </head>
  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" onload="myFunction()">
  <div class="header">
      <div class="bg-color">
        <header id="main-header">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lauraMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
<!--              <a class="navbar-brand" href="#">Laura</a>-->
              <a class="navbar-brand" href="#"><img src="static/img/logo.png" alt="Simple solar" style="height:60px"></a>
            </div>
            <div class="collapse navbar-collapse" id="lauraMenu">
              <ul class="nav navbar-nav navbar-right navbar-border">
                <li class="active" ><a href="{{ url_for('main.video') }}" style="padding:5px 10px; border: solid 2px white; border-radius:15px; font-size:18px;">Understand how Solar Panel </a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>
        <div class="wrapper">
        <div class="container">
          <div class="row">
            <div class="col-md-12 wow fadeIn delay-05s">
              <div class="banner-text">
                <p>Get to know more about the <br>energy output of your <br>Solar Panel</p>
                 <a href="{{url_for('main.where')}}"><div class="text-center btn btn-primary btn-lg">Check your Expected Solar Panel Energy Output</div></a>
              </div>
              <div class="overlay-detail text-center">
              </div>
            </div>
          </div>
          </div>
        </div>
        </div>
      </div>
 <!-- <section id="about" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-right">
          <h2 class="title-text">
            Meet<br><span class="deco">Laura</span> Thomson
          </h2>
        </div>
        <div class="col-md-6 text-left">
          <div class="about-text">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>&nbsp;</p>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>&nbsp;</p>
            <ul class="abt-list">
              <li>- Excepteur sint occaecat cupidatat non proident.</li>
              <li>- Duis aute irure dolor in reprehenderit.</li>
              <li>- Ask the experts.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="portfolio" class="section-padding wow fadeInUp delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="title text-center">Let's <span class="deco">See</span> My Work</h2>
        </div>
        <div class="col-md-12">
          <div id="myGrid" class="grid-padding">
          <div class="col-md-4 col-sm-4 padding-right-zero">
            <img src="img/portfolio01.jpg" class="img-responsive">
            <img src="img/port01.jpg" class="img-responsive">
            <img src="img/port02.jpg" class="img-responsive">
            <img src="img/portfolio01.jpg" class="img-responsive">
          </div>
          <div class="col-md-4 col-sm-4 padding-right-zero">
            <img src="img/portfolio02.jpg" class="img-responsive">
            <img src="img/port01.jpg" class="img-responsive">
            <img src="img/port02.jpg" class="img-responsive">
            <img src="img/portfolio01.jpg" class="img-responsive">
            <img src="img/port03.jpg" class="img-responsive">
          </div>
          <div class="col-md-4 col-sm-4 padding-right-zero">
            <img src="img/port01.jpg" class="img-responsive">
            <img src="img/portfolio01.jpg" class="img-responsive">
            <img src="img/portfolio02.jpg" class="img-responsive">
            <img src="img/port03.jpg" class="img-responsive">
            <img src="img/portfolio02.jpg" class="img-responsive">
            <img src="img/port02.jpg" class="img-responsive">
          </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="testimonial" class="section-padding wow fadeInUp">
    <div class="container">
      <div class="row">
        <h2 class="title text-center">See What Our <span class="deco">Client</span> Are Saying ?</h2>
        <div class="test-sec">
          <div class="col-sm-4">
            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamsed commodo nibh ante facilisis bibendum dolor feugiat at. </p>
            </blockquote>
            <div class="carousel-info">
              <div class="pull-left"> <span class="testimonials-name">John Doe</span> <span class="testimonials-post">CEO,  Company Inc.</span> </div>
            </div>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamsed commodo nibh ante facilisis bibendum dolor feugiat at. </p>
            </blockquote>
            <div class="carousel-info">
              <div class="pull-left"> <span class="testimonials-name">John Doe</span> <span class="testimonials-post">CEO,  Company Inc.</span> </div>
            </div>
          </div>
          <div class="col-sm-4">
            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamsed commodo nibh ante facilisis bibendum dolor feugiat at. </p>
            </blockquote>
            <div class="carousel-info">
              <div class="pull-left"> <span class="testimonials-name">John Doe</span> <span class="testimonials-post">CEO,  Company Inc.</span> </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="contact" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="contact-sec text-center">
            <h2>Want To <span class="deco">Hire</span> Me?</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>

        <div class="col-md-8 col-md-push-2">
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            <form action="" method="post" role="form" class="contactForm">
                <div class="form-group">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                    <div class="validation"></div>
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                    <div class="validation"></div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                    <div class="validation"></div>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                    <div class="validation"></div>
                </div>

                <div class="text-center"><button type="submit" class="btn btn-primary btn-lg">Send Message</button></div>
            </form>
        </div>

      </div>
    </div>
  </section>
  <footer class="footer-2 text-center-xs bg--white">
    <div class="container">
      <!--end row--><!--
      <div class="row">
          <div class="col-md-6">
              <div class="footer">
                  © Copyright Laura Theme. All Rights Reserved
                    <div class="credits">
                        <!--
                            All the links in the footer should remain intact.
                            You can delete the links only if you purchased the pro version.
                            Licensing information: https://bootstrapmade.com/license/
                            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Laura
                        -->
                     <!--   Designed by <a href="https://bootstrapmade.com/">BootstrapMade.com</a>
                    </div>
              </div>
          </div>
          <div class="col-md-6 text-right">
              <ul class="social-list">
                  <li>
                      <a href="#">
                          <i class="fa fa-twitter"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-dribbble"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-vimeo"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-instagram"></i>
                      </a>
                  </li>
              </ul>
          </div>

      </div>
      <!--end row-->
   <!-- </div>
  </footer>-->

    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.bxslider.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/wow.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>

  </body>
</html>

app/templates/space.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SimpleSolar</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto:300,400|Questrial|Satisfy">
    <link rel="stylesheet" type="text/css" href="static/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="static/css/style.css">

    <!-- =======================================================
        Theme Name: Laura
        Theme URL: https://bootstrapmade.com/laura-free-creative-bootstrap-theme/
        Author: BootstrapMade.com
        Author URL: https://bootstrapmade.com
    ======================================================= -->
  </head>
  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" >
  <div id="overlay"></div>
  <div class="header">
      <div class="bg-color">
        <header id="main-header">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lauraMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('main.index') }}">SimpleSolar</a>
            </div>
            <div class="collapse navbar-collapse" id="lauraMenu">
              <ul class="nav navbar-nav navbar-right navbar-border">
                <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
              </ul>
            </div>
          </div>
        </nav>
        </header>




  <section id="contact" class="section-padding wow fadeIn delay-05s">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="contact-sec text-center">
            <h2>Hey <span class="deco">Space explorer  !</span> Read the following data from your space craft!</h2>

          </div>
        </div>

        <div class="col-md-8 col-md-push-2">
            <div id="sendmessage">Your message has been sent. Thank you!</div>
            <div id="errormessage"></div>
            </div>
            <form action="" role="form" class="contactForm">
                <div class="form-group">
                  <label>Barometric Reading (Hg)</label>
                    <input id="barometric" type="number" step="0.01" class="form-control" placeholder="in Hg" name="institution">
                </div>
                <div class="form-group">
                  <label>Wind direction (in degrees)</label>
                    <input id="wind_direction" type="number" step="0.01" class="form-control" placeholder="in degrees" name="institution">
                </div>
                <div class="form-group">
                  <label>Wind speed (in miles/hr)</label>
                    <input id="wind_speed" type="number" step="0.01" class="form-control" placeholder="in miles/hr" name="institution">
                </div>
                <div class="form-group">
                  <label>Humidity (in %)</label>
                    <input id="humidity" type="number" step="0.01" class="form-control" placeholder="in %" name="institution">
                </div>
                <div class="form-group">
                  <label>Temperature (in Farenheit)</label>
                    <input id="temp" type="number" step="0.01" class="form-control" placeholder="in Farenheit" name="institution">
                </div>
                <div>
                <label>Solar Panel Area (in m(squared))</label>
                    <input id="panel_area" type="number" step="0.01" class="form-control" placeholder="in m^2" name="institution">
                </div>
                <div class="form-group">
                  <label>Module Efficiency (in %)</label>
                    <input id="eff" type="number" step="0.01" class="form-control" placeholder="in %" name="institution">
                </div>
                <div class="text-center" >
                  <button type="submit" onclick="getPower()"class="btn btn-primary btn-lg">Proceed</button>
                </div>
            </form>
        </div>

      </div>
    </div>
  </section>
  <footer class="footer-2 text-center-xs bg--white">
    <div class="container">
      <!--end row-->
      <div class="row">
          <div class="col-md-6">
              <div class="footer">
                  © Copyright SimpleSolar. All Rights Reserved
                    <div class="credits">
                        <!--
                            All the links in the footer should remain intact.
                            You can delete the links only if you purchased the pro version.
                            Licensing information: https://bootstrapmade.com/license/
                            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Laura
                        -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade.com</a>
                    </div>
              </div>
          </div>
          <div class="col-md-6 text-right">
              <ul class="social-list">
                  <li>
                      <a href="#">
                          <i class="fa fa-twitter"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-dribbble"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-vimeo"></i>
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <i class="fa fa-instagram"></i>
                      </a>
                  </li>
              </ul>
          </div>

      </div>
      <!--end row-->
    </div>
  </footer>

    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/jquery.easing.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/jquery.bxslider.min.js"></script>
    <script src="static/js/wow.js"></script>
    <script src="static/js/custom.js"></script>
    <script>

    function getPower() {
      $("body").append('<div id="overlay" style="background-color:grey;position:absolute;top:0;left:0;height:100%;width:100%;z-index:999></div>');
      var pressure = parseFloat($("#barometric").val());
      var humidity = parseFloat($("#humidity").val());
      var wind_speed = parseFloat($("#wind_speed").val());
      var temp = parseFloat($("#temp").val());
      var efficiency = parseFloat($("#eff").val());
      var size = parseFloat($("#panel_area").val());
      var wind_direction = parseFloat($("#wind_direction").val());
      $.getJSON('http://localhost:5000/api/v1/predict?barometric='+pressure+'&humidity='+humidity+'&speed='+wind_speed+'&temp='+temp+'&eff='+efficiency+'&panel_area='+size+'&direction='+wind_direction)
   .done (function(power)
   {
     $(location).attr('href', 'http://localhost:5000/appliance/'+power.total)
    });
    }
    </script>

  </body>
</html>